apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: my-cluster-dual-role
  namespace: monitoring
  labels:
    release: prometheus # match this in prometheusSpec.podMonitorSelector
spec:
  namespaceSelector:
    matchNames: ["strimzi"]
  selector:
    matchLabels:
      strimzi.io/cluster: my-cluster
      strimzi.io/kind: Kafka
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s
