grafana:
  persistence:
    type: pvc
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    finalizers:
      - kubernetes.io/pvc-protection
  grafana.ini:
    server:
      domain: localhost
      root_url: "https://%(domain)s/grafana"
      serve_from_sub_path: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    externalUrl: https://localhost/prometheus
    routePrefix: /prometheus
    additionalScrapeConfigs:
      - job_name: traefik
        metrics_path: "/metrics"
        scrape_interval: 10s
        scrape_timeout: 5s
        scheme: http
        static_configs:
          - targets:
              - "traefik.traefik.svc.cluster.local:9100"
      - job_name: jaeger-collector
        metrics_path: "/metrics"
        scrape_interval: 10s
        scrape_timeout: 5s
        scheme: http
        static_configs:
          - targets:
              - "jaeger-collector.monitoring.svc.cluster.local:14269"
      - job_name: jaeger-query
        metrics_path: "/metrics"
        scrape_interval: 10s
        scrape_timeout: 5s
        scheme: http
        static_configs:
          - targets:
              - "jaeger-query.monitoring.svc.cluster.local:16687"
      # Strimzi Kafka Exporter metrics

# prometheus.prometheusSpec.routePrefix
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
    mountPropagation: HostToContainer
