global:
  security:
    allowInsecureImages: true

image:
  registry: registry-1.docker.io
  repository: bitnamisecure/redis
  tag: latest

metrics:
    enabled: true
    image:
      registry: registry-1.docker.io
      repository: bitnamisecure/redis-exporter
      tag: latest
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
      interval: 10s
      scrapeTimeout: 5s
      

auth:
  enabled: true
  password: "test-redis"

master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard"

replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard"

