"""fix field email_verified

Revision ID: 3c5b554084ec
Revises: 06a59a98a5aa
Create Date: 2025-07-30 09:49:15.559968

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import false

# revision identifiers, used by Alembic.
revision: str = '3c5b554084ec'
down_revision: str | None = '06a59a98a5aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), nullable=False, default=False, server_default=false()))
    op.drop_column('users', 'email_verifies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verifies', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
