architecture: "replication"

auth:
  user: "user"
  postgresPassword: "newPostgresPassword123"
  password: "newUserPassword123"
  replicationPassword: "newReplicationPassword123"

passwordUpdateJob:
  enabled: true

primary:
  persistence:
    size: 4Gi
    storageClass: standard
readReplicas:
  persistence:
    size: 4Gi
    storageClass: standard
