cassandra:
  persistence:
    enabled: true
    storageClass: standard # Set this to an available storage class
    size: 2Gi # Example size, adjust based on your needs

query:
  extraEnvVars:
    - name: QUERY_BASE_PATH
      value: "/tracing"
    - name: METRICS_STORAGE_TYPE
      value: prometheus
    - name: PROMETHEUS_SERVER_URL
      value: http://prometheus-operated.monitoring.svc.cluster.local:9090/prometheus/

monitoring:
  enabled: true
  prometheus:
    scrape: true
    serviceMonitor:
      enabled: true
