---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger
  namespace: monitoring
spec:
  entryPoints:
    - web
    - test-port
  routes:
    - kind: Rule
      match: "Host(`localhost`) && PathPrefix(`/tracing`)"
      services:
        - kind: Service
          name: jaeger-query
          port: 16686
