apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-operated
  namespace: monitoring
spec:
  entryPoints:
    - web # Switch to secure entry point for HTTPS
    - test-port
  routes:
    - kind: Rule
      match: Host(`localhost`) && PathPrefix(`/prometheus`)
      services:
        - kind: Service
          name: kube-prometheus-stackr-prometheus
          port: 9090
