---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: "users"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          # image: docker.io/library/cognito:latest
          # imagePullPolicy: Never
          image: datahub_polyglot_users:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: other-envs
          resources:
            limits:
              memory: "512Mi"
              cpu: "900m"
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000
              path: /users/health
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 8000
              path: /users/health
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
