apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - web
    - test-port
  routes:
    - kind: Rule
      match: "Host(`localhost`) && PathPrefix(`/grafana`)"
      # middlewares:
      #   - name: grafana-prometheus-strip
      #     namespace: traefik
      services:
        - kind: Service
          name: kube-prometheus-stackr-grafana
          port: 80
